version: '3.8'

services:
  server:
    image: server_image:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"

  tests:
    image: tests_image:latest
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
