name: Deploy application

on:
  workflow_run:
    workflows: [ "Static Checks" ]
    types:
      - completed
  

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USR }}
          password: ${{ secrets.DH_PSW }}
      - name: Build image
        run: |
          docker-compose build server
      - name: Tag the Docker image
        run: |
          docker tag server_image:latest ${{ secrets.DH_REP_NAME }}:latest
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DH_REP_NAME }}:latest
